export class CollectionRecord{
    id: bigint;
    caseId: bigint;
    orderId: bigint;
    contactStatus: string;
    contactName: string;
    contactPhone: string;
    communicationStatus: string;
    answerStatus: string;
    remark: string;
    checkStatus: boolean;
    collectorId: number;
    strategy: string;
    customerId: bigint;
    seatId: string;;
    collectorName: string;
    promiseRefundTime: string;
    promiseRefundAmount: string;
    updateTime: string;
    createTime: string;
    product: string;
    invokeId: string;
    orderNo: string;
    caseStatus: string;
    province: string;
    city: string;
    industryChanged: string;
    industry: string;
}